---
 
 - hosts: all
   become: true
   pre_tasks:
 
#   - name: install updates (Ubuntu)
#     tags: always
#     apt:
#       upgrade: dist
#       update_cache: yes
#     when: ansible_distribution == "Ubuntu"
  
# - hosts: all
#   become: true
#   tasks:
 
#   - name: install apache2 package (Ubuntu)
#     tags: apache,apache2,ubuntu
#     apt:
#       name:
#         - apache2
#         - libapache2-mod-php
#       state: latest
#     when: ansible_distribution == "Ubuntu"
 
   - name: copy html files to server
     tags: apache2,ubuntu
     copy:
       src: files/default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
